### ISSUE TITLE
Problem with encoded file URL's

### ISSUE THREAD

**Issue by joaoribeirost** [moumar/ruby-audioinfo#12]
I'm trying to open a sound file from AmazonS3 bucket with authentication needed, which means the file URL is like .wav?TOKENS. This takes to a "unsuported extension". 

Is there a way to tell AudioInfo which extension the file is?

**Comment by jaredmoody** [comment]
The AudioInfo constructor takes the file extension as a second argument, so you can do something like:

`AudioInfo.new(tempfile_path, "wav")`

Sorry you had to wait 5 years for an answer :P
