### ISSUE TITLE
AudioInfo.new("file", "utf-8") desn't work

### ISSUE THREAD

**Issue by ghlkp** [moumar/ruby-audioinfo#14]
The Readme says:

"unified support for tag text-encoding. AudioInfo.new("file", "utf-8") and you're done!"

Unfortunately, this doesn't work:

irb(main):002:0> a=AudioInfo.new("file", "utf-8")
ArgumentError: wrong number of arguments (2 for 1)
        from /usr/lib64/ruby/gems/2.1.0/gems/ruby-audioinfo-0.5.2/lib/audioinfo.rb:75:in `initialize'
        from (irb):2:in`new'
        from (irb):2
        from /usr/bin/irb:11:in `<main>'

**Comment by jaredmoody** [comment]
The README was corrected, `AudioInfo.new` takes a single argument, the file.
