### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by jaredmoody** [moumar/ruby-audioinfo#19]
Is this repo abandoned? If so, I'd be happy to take over as the maintainer. If not let me know and I'd like to contribute at least a pull request to fix #6

**Comment by moumar** [comment]
hello Jared,

yes this project is unmaintained, i'll promote you as the maintainer.

Thank you !

**Comment by jaredmoody** [comment]
@moumar great, thanks!

I've prepared 0.5.4 but can't release it because I'm not an owner on rubygems. Can you make me an owner with `gem owner ruby-audioinfo --add jared@jaredmoody.com` ?

Or, if you would prefer not to make me an owner, can you release a new version with `rake release` ?

Thanks!

**Comment by moumar** [comment]
i just added you as rubygems owner on this project !
Thanks
