### ISSUE TITLE
Interferes with database connection when used with Rails

### ISSUE THREAD

**Issue by malomalo** [moumar/ruby-audioinfo#2]
Not sure how but when uploading a file to Rails and calling AudioInfo on the uploaded file as a before_save hook to set the audio length in the database Rails will always throw the following error:

`Mysql2::Error: MySQL server has gone away: INSERT INTO.....`

gist of model and stack trace: https://gist.github.com/16a896402ce7747a6b65
## Gems
- rails 3.1.1
- paperclip 2.3.16
- aws-s3 0.6.2
- ruby-audioinfo 0.1.7
- mysql2 0.3.7
- therubyracer 0.9.8
- postmark-rails 0.4.1

**Comment by akichim21** [comment]
this problem is caused by fork.
https://github.com/moumar/ruby-audioinfo/blob/master/lib/audioinfo.rb#L382

when child process generated by fork close, mysql connection close together.
can you change or delete fork?

**Comment by jaredmoody** [comment]
It looks like this was a bug with `mysql2` that has been resolved and this issue can be closed.

**Comment by jaredmoody** [comment]
We still need to remove the usage of fork to deal with #11, but will track updates on that ticket.
